### ISSUE TITLE
Missing required_message in Export to XLSForm

### ISSUE THREAD

**Issue by khaled-alshamaa** [opendatakit/build2xlsform#8] opened 2019-03-17 12:24 UTC
Tested version is: ODK Build 0.3.5 (offline version on Windows 64-bit OS)
Required text does not exported (i.e. there is no required_message column) in use the Export to XLSForm functionality in the File menu, even they are exists in the exported XML file when use the Export to XForm functionality.

**Comment by yanokwa** [comment] 2019-03-17 19:18
Confirmed that the required message is in the Export to XML, but not in the Export to XLSForm.

**Comment by khaled-alshamaa** [comment] 2019-03-17 23:12
Same issue exists also when tested on the [ODK Build - Online version](https://build.opendatakit.org/) _visited in Mar 17, 2019_

**Comment by issa-tseng** [comment] 2019-03-20 22:15
:( oops. thanks for the report!

**Comment by khaled-alshamaa** [comment] 2019-04-21 06:33
Any updates?

**Comment by issa-tseng** [comment] 2019-04-23 18:43
hey khaled, sorry we haven't gotten to this yet. because Build releases take quite a bit of time to put together, we tend to wait a little bit and batch some fixes up. that, combined with the fact that most of my attention is on ODK Central right now and nobody else works on Build with me, means that it may be some months more before we release a fix for this. :(

**Closed as completed** 2019-05-27 16:57 UTC

**Comment by khaled-alshamaa** [comment] 2019-05-28 14:07
When/where I can test it? The online version of [ODK Build](https://build.opendatakit.org/) still not fixed (visited in May 28, 2019)

**Comment by issa-tseng** [comment] 2019-05-28 17:25
hi khaled: i will try to get a release out later this week.

**Comment by issa-tseng** [comment] 2019-06-04 06:30
hi khaled: some new things came up to make a full new version of Build a sensible proposition, but it'll be a little bit before i can make that happen. in the meantime, i've custom-built you this version that should have your issue fixed. please let me know if it doesn't work for you.

https://www.dropbox.com/s/2a5ce7kgykra0hy/nwjs%20x64%200.24.0.zip?dl=0
